branch-defaults:
  master:
    environment: bcomplydev
environment-defaults:
  bcomplydev:
    branch: null
    repository: null
global:
  application_name: bcomply
  default_ec2_keyname: timkeypair
  default_platform: 64bit Amazon Linux 2018.03 v2.9.1 running PHP 7.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
