branch-defaults:
  master:
    environment: bcomplydev
global:
  application_name: bcomply
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2018.03 v2.9.1 running PHP 7.3
  default_region: us-east-1
  profile: eb-cli
  sc: git
